name: release

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform:
        - os: ubuntu-20.04
          target: x86_64-unknown-linux-musl
        - os: macos-11
          target: x86_64-apple-darwin
        # TODO: provide aarch64 builds
    runs-on: ${{ matrix.platform.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L '.#enarx-static'
    - run: ./result/bin/enarx info
    - uses: actions/upload-artifact@v3
      with:
        name: enarx-${{ matrix.platform.target }}
        path: result/bin/enarx
    - run: nix build -L '.#enarx-docker'
    - run: docker load < enarx-docker
    - uses: actions/upload-artifact@v3
      with:
        name: enarx-docker-${{ matrix.platform.target }}
        path: result

  release:
    if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - uses: actions/download-artifact@v3
    - uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          enarx-docker-x86_64-apple-darwin
          enarx-docker-x86_64-unknown-linux-musl
          enarx-x86_64-apple-darwin
          enarx-x86_64-unknown-linux-musl
